name: Release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install FUSE
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: ⚡ Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            agent/target
            extensions/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js with Corepack
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build project
        run: pnpm make build

      - name: Generate Changelog
        id: changelog
        run: |
          pnpm changelogithub --output RELEASE.md

      - name: Pack as AppImage
        run: pnpm make pack --appimage

      - name: Pack as tar.gz and tar.xz
        run: pnpm make pack --archive

      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/target/

  build_flatpak_repo:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: ⚡ Cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-flatpak-${{ hashFiles('**/dev.sallon.lenz.flatpak.yaml') }}
          path: |
            ~/.flatpak-builder
            ~/.ccache
      - name: Install Flatpak dependencies
        run: |
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak --user install -y flathub org.freedesktop.Platform//25.08 org.freedesktop.Sdk//25.08 org.freedesktop.Sdk.Extension.rust-stable//25.08 org.freedesktop.Sdk.Extension.node22//25.08
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Flatpak repo
        run: |
          mkdir -p dist/target
          mkdir -p flatpak
          flatpak-builder --disable-rofiles-fuse --gpg-sign="contato@sallon.dev" --repo=repo --force-clean --ccache build-dir dev.sallon.lenz.flatpak.yaml
          flatpak build-bundle --gpg-sign="contato@sallon.dev" repo flatpak/dev.sallon.lenz.flatpak dev.sallon.lenz
          mv repo flatpak/repo

      # Assinar o repositório Flatpak
      - name: Sign Flatpak repository
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --sign
          flatpak build-update-repo --gpg-sign="contato@sallon.dev" flatpak/repo
          flatpak build-sign flatpak/repo --gpg-sign="contato@sallon.dev"

      - name: "Create FlatpakRepo"
        env:
          GPG_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        run: |
          cat <<EOF > flatpak/lenz.flatpakrepo
          [Flatpak Repo]
          Title=Lenz Designer
          Url=https://sallon.dev/lenz/flatpak
          Homepage=https://sallon.dev/lenz
          Comment=Repositório de atualizações do Lenz Designer
          Description=Repositório de atualizações do Lenz Designer
          Icon=https://sallon.dev/lenz/logo.png
          GPGKey=$GPG_KEY
          EOF
          echo $GPG_KEY | base64 -d > flatpak/lenz.gpg

      - name: "Create FlatpakRef"
        env:
          GPG_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        run: |
          cat <<EOF > flatpak/lenz.flatpakref
          [Flatpak Ref]
          Title=Lenz Designer
          Name=dev.sallon.lenz
          Branch=master
          Runtime=org.freedesktop.Platform//24.08
          Url=https://sallon.dev/lenz/flatpak
          Arch=x86_64
          Comment=Um editor de páginas HTML para todos
          Icon=dev.sallon.lenz
          License=GPL-3.0-or-later
          GPGKey=$GPG_KEY
          EOF

      - name: Upload flatpak artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flatpak
          path: flatpak

  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build docs
        run: pnpm build:docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs

  organize_artifacts:
    needs: [build_binaries, build_flatpak_repo, build_docs]
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist/target

      - name: Download flatpak repo artifacts
        uses: actions/download-artifact@v4
        with:
          name: flatpak
          path: flatpak

      - name: Download docs artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs

      - name: Update VERSION in install script
        run: |
          sed -i "0,/VERSION=.*/{s//VERSION=\"${{github.ref_name}}\"/;b};" docs/install.sh

      - name: Move flatpak repo to github_pages
        run: |
          mv flatpak/lenz.flatpakrepo docs/lenz.flatpakrepo
          mv flatpak/lenz.flatpakref docs/lenz.flatpakref
          mv flatpak/lenz.gpg docs/lenz.gpg
          mv flatpak docs/flatpak

      - name: Upload docs to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  create_release:
    needs: [organize_artifacts, build_binaries]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js with Corepack
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install
      - name: Generate Changelog
        id: changelog
        run: |
          pnpm changelogithub --output RELEASE.md
      - name: Download binaries artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          body_path: RELEASE.md
          files: |
            lenz-designer.AppImage
            lenz-designer.tar.gz
            lenz-designer.tar.xz

  deploy_pages:
    needs: [organize_artifacts, create_release]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
